import type { Usage } from '../../models/Entry';
import { aiActiveFor, aiEntry, aiStatus } from '../../state/aiAssist';
import { llmEnabled, llmProgress } from '../../state/llm';
import { requestPageAi } from '../AiModal/aiModal';
import Icon from '../Icon/Icon.tsx';
import './aiAssist.scss';

interface AiAssistProps {
  word: string;
}

const UsageLine = ({ label, usages }: { label: string; usages: Usage[] }) => {
  if (usages.length === 0) return null;
  return (
    <div className="ai-assist__usage-group">
      <span className="ai-assist__register">{label}</span>
      {usages.map((usage) => (
        <p key={usage.finglish} className="ai-assist__usage">
          <span className="ai-assist__usage-fa">{usage.finglish}</span>
          <span className="ai-assist__usage-en">{usage.english}</span>
        </p>
      ))}
    </div>
  );
};

const AiAssist = ({ word }: AiAssistProps) => {
  const active = llmEnabled.value || aiActiveFor.value === word;

  if (!active) {
    return (
      <button type="button" className="ai-assist__enable" onClick={() => requestPageAi(word)}>
        <Icon name="sparkles" />
        Show AI Assistant
      </button>
    );
  }

  const phase = aiStatus.value;
  if (phase === 'idle') return null;

  if (phase === 'loading') {
    const progress = llmProgress.value;
    const percent = progress.total ? Math.round((progress.loaded / progress.total) * 100) : 0;
    const downloading = progress.status === 'loading' && percent > 0;
    return (
      <section className="ai-assist ai-assist--status">
        <Icon name="sparkles" />
        <span>{downloading ? `Loading on-device model… ${percent}%` : 'AI is thinking…'}</span>
      </section>
    );
  }

  const entry = aiEntry.value;
  if (phase === 'error' || !entry) {
    return (
      <section className="ai-assist ai-assist--status">
        <Icon name="sparkles" />
        <span>The on-device AI could not produce an answer this time.</span>
      </section>
    );
  }

  const informal = entry.usages.filter((usage) => usage.register === 'informal');
  const formal = entry.usages.filter((usage) => usage.register === 'formal');

  return (
    <section className="ai-assist">
      <h3 className="ai-assist__title">
        <Icon name="sparkles" />
        AI assist
      </h3>
      <p className="ai-assist__meaning">
        <strong>{entry.term}</strong> — {entry.meaning}
      </p>
      <UsageLine label="Informal" usages={informal} />
      <UsageLine label="Formal" usages={formal} />
      {entry.note && <p className="ai-assist__note">{entry.note}</p>}
      <p className="ai-assist__disclaimer">
        Generated by a small on-device model — may be inaccurate. The dictionary entries above are
        the reliable source.
      </p>
    </section>
  );
};

export default AiAssist;
